// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import NavBar from "@/components/navbar/page";
// import NotFound from "./not-found";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   useEffect(() => {
//     AOS.init({
//       duration: 1000, // مدة الحركة بالمللي ثانية
//       once: true,     // يتنفذ مرة واحدة فقط
//     });
//   }, []);
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
  
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <NavBar />

//         {children}
      
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavBar from "@/app/components/navbar/page";
import Footer from "@/app/components/footer/page";
import WhatsAppButton from "@/app/components/whatsApp/page";
import { ParamsLocale, SupportedLocales } from '@/types/globals';
import { getDictionary } from "@/lib/utils/dictionary";
import React from "react";
import 'aos/dist/aos.css'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{ children: React.ReactNode, params: ParamsLocale }>) {
  const {lang} = await params;


  const dir = lang === 'ar' ? 'rtl' : 'ltr'
  const dict = await getDictionary(lang)

  return (
    <html lang={lang} dir={dir}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="fixed top-0 left-0 w-full h-screen bg-gradient-to-tr from-[#f8e6bc] from-45% to-[#f8f4f0]   to-100% -z-10"></div>
         <NavBar dict={dict}/>
        {children}
        <WhatsAppButton dict={dict}/>
        <Footer dict={dict}/>
      </body>
    </html>
  );
}


